# Production configuration (default)
spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
    # password: # Set via environment variable

---
spring:
  profiles: development
  devtools:
    livereload:
      enabled: true
  session:
    store-type: none

# spring.profiles.active: redis
#    redis:
#      password:
#      host:
#      port:
